name: masdamas
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  carousel_pro: ^1.0.0
  dio: 3.0.10
  flutter:
    sdk: flutter

  getwidget: ^1.1.0
  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core:
    ^0.5.3
    # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^6.3.0
  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.18.4+1
  cloud_firestore: "^0.14.0+2"
  path_provider:
  path:
  cupertino_icons: ^1.0.0
  enum_to_string: ^1.0.14
  firebase_storage: ^5.2.0
  firebase_database: ^4.0.0
  provider:
  modal_progress_hud: ^0.1.3
  
  google_sign_in: ^4.5.6
  image_picker: ^0.6.7+21
  splashscreen:
  flutter_launcher_icons:
  generic_bloc_provider: ^1.0.9
  fluttertoast: ^7.1.6
  get_it: ^4.0.2
  flutter_svg: ^0.18.0
  auto_size_text: ^2.1.0
  auto_search: ^1.0.6
  camera: ^0.7.0+2
  tflite: ^1.1.1
  cached_network_image:
  simple_image_crop: ^0.1.3
  http: ^0.12.2
  flutter_widget_from_html: ^0.5.2
  flutter_multi_carousel: ^1.0.0
  qr_code_scanner: ^0.3.5
  flutter_mobile_carousel: ^1.0.3
  speech_recognition: ^0.3.0+1
  pin_code_fields: ^6.1.0
  flutter_phoenix: ^0.1.0
  local_auth: ^0.6.3+4
  encrypt: ^4.1.0
  flutter_secure_storage: ^3.3.5
  shared_preferences: ^0.5.12
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^4.0.1+2
  photo_view: ^0.10.3
  flutter_chat_bubble: ^1.0.0
  flutter_rating_bar: ^3.2.0+1
  flutter_tags: ^0.4.9+1
  future_progress_dialog: ^0.1.1
  intl: ^0.16.1
  logger: ^0.9.4
  permission_handler: ^5.0.1+1
  pinch_zoom_image: "^0.2.4"
  string_validator: ^0.1.4
  swipedetector: ^1.2.0
  url_launcher: ^5.7.10


dev_dependencies:
 flutter_test:
   sdk: flutter

flutter_launcher_icons: "^0.7.0"
flutter_icons:
  image_path: 'assets/images/simbolo.png'
  android: true
  ios: true
 
camera:
  git:
    url: https://github.com/flutter/plugins.git
    path: packages/camera/camera
    ref: cfa709835ab85702ee8a9ed24bbe7a3fe736c3f5
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Cicons
      fonts:
        - asset: fonts/Cicons.ttf

    - family: Futura
      fonts:
        - asset: fonts/FuturaMediumBT.ttf

    - family: Menu
      fonts:
        - asset: fonts/Menu.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/users/
    - assets/video/
    - assets/model_unquant.tflite
    - assets/labels.txt


 


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
