/// Flutter icons Menu
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Menu
///      fonts:
///       - asset: fonts/Menu.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Menu {
  Menu._();

  static const _kFontFam = 'Menu';
  static const _kFontPkg = null;

  static const IconData casa_negro =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camara =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compartir =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData canasta_negra =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData miespacio_negro =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pareja_negro =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
